services:
  postgres:
    image: postgres:15
    volumes:
      - db_postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=gestionTransporte
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dbgt
volumes:
  db_postgres:

